# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
# print(A) # whole matrice
print(A.ndim) # dimension of the matrice
print(A.shape) # size of matrice n x m
print(A.size) # number of elements in the matrice
print(A.dtype) # datatype of elements

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
B-C # Elementwise subtraction.

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [6]:
B*C # Elementwise multiplication

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [7]:
B@C # Matrice multiplication

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [8]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
np.exp(B) # every element exponentiated

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [10]:
np.min(B) # the smallest value in the matrice

1

In [11]:
print(np.min(B[0])) # printing the smallest value in first row (1,2,3)
print(np.min(B[1])) # printing the smallest value in second row (4,5,6)
print(np.min(B[2])) # printing the smallest value in third row (7,8,9)

print(np.min(B, axis=1)) # an alternative way to do the same calculation

1
4
7
[1 4 7]


In [12]:
print(np.min(B[:,0])) # printing the smallest value in first column (1,4,7)
print(np.min(B[:,1])) # printing the smallest value in second column (2,5,8)
print(np.min(B[:,2])) # printing the smallest value in third column (3,6,9)

print(np.min(B, axis=0)) # an alternative way to do the same calculation

1
2
3
[1 2 3]


In [13]:
print(np.argmin(B)) # find the index for the smallest value in the matrice with use.np.argmin
print(np.argmin(B, axis=0)) # find the index for the smallest value in each row

0
[0 0 0]


In [14]:
print(np.sum(B)) # the sum of all elements
print(np.mean(B, axis=0)) # mean per column
print(np.median(B, axis=0)) # median per column

# jag ser att lösningsförslag har angett axis=1, men axis=0 bör vara matematiskt korrekt
# ty 1+4+7 = 12 12/3=4 2+5+8=15 15/3=5 3+6+9=18 18/3=6
# axis=1 ger medelvärden för varje rad

45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [15]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [16]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [17]:
# I will get all the elements in the the second row with index=1
# Wbvhen fewer indices are provided than the number of axes, the missing indices are considered complete slices

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [18]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [20]:
for i in np.nditer(A): # works but gets order from memory so there's probably another solution/function to use
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [21]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [22]:
# code creates a matrice a with one row and 30 elements 0 to 29
# code reshapes the values of matrice a to matrice b
# in shape with 3 dimensions, 2 axes, three rows (first axis has legth of 3) and as many colums as needed (-1) for the 30 elements
# prints matrice a, empty line and matrice b

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [23]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [24]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [25]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [26]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [27]:
F = 'string'

def add_mult_matrice(mat_a, mat_b, choice):
    """ function that takes two matrices and multiply or add them mathematical correct"""
    if isinstance(mat_a, np.ndarray) and isinstance(mat_b, np.ndarray): # check if variables is ndarray
              
        if choice == 'add': # if choice is to add
            if mat_a.shape == mat_b.shape: # and they have the same size
                return(mat_a+mat_b) # add matrices
            else:
                print('Matrices are not of same size so no addition is proceeded') # if not send message
                
        elif choice == 'multiply': # if choice is to multiply
            rows_a, cols_a = mat_a.shape
            rows_b, cols_b = mat_b.shape
    
            if cols_a == rows_b: # check that size of column in a is the same as row in b
                 return(mat_a@mat_b)
            else:
                print('Columns of first matrice does not match rows of second matrice, no multiply has proceeeded') # if not send message

        else:
            print('You have too choose add or multiply') # if choice is not add or multiply send message     
        
    else:
        print ('One or both of arguments are not an matrice') # if matrices is not same size send message

add_mult_matrice(A, B, 'add')

array([[ 6, -1,  0],
       [ 3, -5, -1]])

In [28]:
add_mult_matrice((B), (-2*A), 'add') # trying to calculate B-2A

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [29]:
add_mult_matrice((3*C), (-1*E), 'add') # trying to calculate 3C-E

Matrices are not of same size so no addition is proceeded


In [30]:
add_mult_matrice(A, C, 'multiply') # trying to calculate A*C

Columns of first matrice does not match rows of second matrice, no multiply has proceeeded


In [31]:
add_mult_matrice(C, D, 'multiply') # trying to calculate C*D

array([[11, 10],
       [10, 11]])

In [32]:
add_mult_matrice(C, B, 'multiply') # trying to calculate C*B

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

**Chap2. Question 2**

In [33]:
A2 = np.array([[1, 2], [2, 4]])
B2 = np.array([[2, 1], [1, 3]])
C2 = np.array([[4, 3], [0, 2]])

AB = add_mult_matrice(A2, B2, 'multiply')
AC = add_mult_matrice(A2, C2, 'multiply')

if AB.all() == AC.all(): # check if all elements in AB and AC are the same
    print('AB = AC')

if B2.all() is not C2.all(): # check if all elements in B and C are not the same
    print ('B =! C')

AB = AC
B =! C


**Chap2. Question 3**

In [34]:
A3 = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]]) # creating matrices
D3 = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

print(add_mult_matrice(A3, D3, 'multiply')) # multipling matrices with function
print()
print(add_mult_matrice(D3, A3, 'multiply'))

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [35]:
A4 = np.array([[1, -1], [-1, 1]])
B4 = np.array([[-1, 1], [1, -1]])

print (add_mult_matrice(A4, B4, 'multiply'))

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [36]:
A5 = np.array([[5, 6], [4, 5]])
B5 = np.array([[6, 4], [3, 3]])

# find the inverse  = 1/(ad-bc) ([d,-b],[-c,a])
print(np.linalg.inv(A5)) # using linalg.inv() to find the inverse of the matrices
print()
print(np.linalg.inv(B5))

[[ 5. -6.]
 [-4.  5.]]

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [37]:
A6 = np.array([[2, 2], [1, 2]])
np.linalg.inv(A6) # using linalg.inv() to find the inverse of the matrices

array([[ 1. , -1. ],
       [-0.5,  1. ]])

**Chap10. Question 1 a)**

In [38]:
gauss_a = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])

vect_a = np.array([[1], [1], [1]])

array_a = np.array([[-7], [5], [2]])

gauss_ai = np.linalg.inv(gauss_a) # using linalg.inv() to find the inverse of the matrices
vect_a=add_mult_matrice(gauss_ai, array_a, 'multiply')  # using function to multiply inverse with array_a to give vect_a values
print(vect_a)

add_mult_matrice(gauss_a, vect_a, 'multiply') # check if solution is right

[[ 3.]
 [ 4.]
 [-6.]]


array([[-7.],
       [ 5.],
       [ 2.]])

**Chap10. Question 1 b)**

In [39]:
gauss_b = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])

vect_b = np.array([[1], [1], [1]])

array_b = np.array([[1], [-1], [1]])

gauss_bi = np.linalg.inv(gauss_b) # using linalg.inv() to find the inverse of the matrices
vect_b=add_mult_matrice(gauss_bi, array_b, 'multiply')  # using function to multiply inverse with array_b
print(vect_b)

add_mult_matrice(gauss_b, vect_b, 'multiply') # check if solution is right

[[ 8.]
 [ 2.]
 [-1.]]


array([[ 1.],
       [-1.],
       [ 1.]])

**Chap 12. Question 1**

In [40]:
lec_12 = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, -0]])
np.linalg.inv(lec_12)

array([[ 0.66666667,  1.33333333,  0.5       ],
       [ 1.        ,  2.        ,  0.5       ],
       [-3.        , -5.        , -1.        ]])

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [41]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [42]:
print(v1.base)
print(v2.base)
# The base attribute of a view returns the original array while it returns None for a copy.

None
[0 1 2 3]


In [43]:
v2[-1] = 123
print(v1)
print(v2)
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.

# since v2.base returns the attribute in the second line, it tells us that v2 is a view.
# if you change a view, you change the original object
# if you instead makes a copy (or deep copy) of the original object and changes it the original will stay intact

[  0   1   2 123]
[  2 123]


In [44]:
v3 = v1.copy()
print('v3-array:', v3)
print('v3-base:', v3.base)
v3[-2] = 1234
print('changed v3-array:', v3)
print('v1-array:', v1)
# since v3 is a copy (v3.base returns None) of the object v1, v1 won't be affected by the changes made in v3.

v3-array: [  0   1   2 123]
v3-base: None
changed v3-array: [   0    1 1234  123]
v1-array: [  0   1   2 123]
